Contacts
VladimirBludov/team-project-ice-cream pull request #11
Opened 2021-12-02 20:37 UTC by Lezhnova

2021-12-03 11:13 UTC, VladimirBludov requested changes

2021-12-03 11:13 UTC, VladimirBludov commented on src/images/icons.svg
> +
убери пустые строки

2021-12-03 11:13 UTC, VladimirBludov commented on src/partials/contacts.html
> +                          06:00 AM - 10:00 PM
время отличается, поправь во всех карточках

2021-12-03 11:13 UTC, VladimirBludov commented on src/sass/_contacts.scss
> +  padding-top: 85px;
добавь к padding-top: 85px; еще 43, чтобы секция отступила от предыдущей

2021-12-03 11:13 UTC, VladimirBludov commented on src/sass/_contacts.scss
> +    padding-top: 78px;
а здесь + 60

2021-12-03 11:13 UTC, VladimirBludov commented on src/sass/_contacts.scss
> +  padding-right: 50px;
падинги закрывай в медиазапрос для телефона, чтобы не переопределялись

везде пересмотри, если что-то переопределяется, то закрывай в соответствующий медиазапрос

2021-12-03 11:13 UTC, VladimirBludov commented on src/sass/_contacts.scss
> +  align-items: center;
текст выравнивается падингами а не флексом

2021-12-03 11:13 UTC, VladimirBludov commented on src/sass/_contacts.scss
> +  font-style: normal;
нормал быть не должно быть, они по умолчанию, пересмотри везде, поудаляй

2021-12-03 11:13 UTC, VladimirBludov commented on src/partials/contacts.html
> +                <address class="contact__address">
в адрес оборачивается, только сам адрес, например 1664 S Blue Island Avenu, Chicago, IL 60608, USA
исправь во всех карточках

2021-12-03 11:13 UTC, VladimirBludov commented on src/sass/_contacts.scss
> +  margin-bottom: 20px;
margin-bottom: 20px; не должно быть у последней карточки

2021-12-03 11:13 UTC, VladimirBludov commented on src/sass/_contacts.scss
> +  transform: translateY(-85px);
сдвигай не контейнер а список, а то внизу падинг не получится нормально выставить, сейчас расстояние до футера 85, а должно быть 56

2021-12-03 11:13 UTC, VladimirBludov commented on src/sass/_contacts.scss
> +  font-weight: bold;
font-weight: bold; только цифры, везде проверь font-weight: 700;

2021-12-03 11:13 UTC, VladimirBludov commented on src/sass/_contacts.scss
> +    flex-basis: calc((100% - 60) / 3);
flex-basis: calc((100% - 60) / 3); они у тебя негде не работаю, должно быть flex-basis: calc((100% - 60px) / 3);

2021-12-03 12:02 UTC, Lezhnova commented on src/sass/_contacts.scss
> +    flex-basis: calc((100% - 60) / 3);
готово

2021-12-03 12:03 UTC, Lezhnova commented on src/sass/_contacts.scss
> +  font-weight: bold;
готово

2021-12-03 12:06 UTC, Lezhnova commented on src/images/icons.svg
> +
+

2021-12-03 12:12 UTC, Lezhnova commented on src/sass/_contacts.scss
> +  padding-top: 85px;
готово)

2021-12-03 12:15 UTC, Lezhnova commented on src/sass/_contacts.scss
> +    padding-top: 78px;
готово

2021-12-03 12:32 UTC, Lezhnova commented on src/partials/contacts.html
> +                          06:00 AM - 10:00 PM
готово

2021-12-05 03:33 UTC, VladimirBludov approved these changes

2021-12-05 03:34 UTC, merged