Origin header
VladimirBludov/team-project-ice-cream pull request #12
Opened 2021-12-02 23:17 UTC by AlinaSenkovich

2021-12-03 10:11 UTC, VladimirBludov commented
Добавь скрипт открытия мобильного меню

2021-12-03 10:11 UTC, VladimirBludov requested changes

2021-12-03 10:11 UTC, VladimirBludov commented on src/partials/header.html
> +  <a  class="link header__logo" href=""><img src="images/header/logo 1.png" alt="logo"></a>
изображение не адоптировано под 2x и 3x

2021-12-03 10:11 UTC, VladimirBludov commented on src/partials/header.html
> +  <div class="conteiner header__conteiner">
conteiner написан с ошибкой и не применяется, исправь на container

2021-12-03 10:11 UTC, VladimirBludov commented on src/partials/header.html
> +              <li class="mobile-nav__item"><a class="mobile-nav__link link" href="">Home</a></li>
нет якорей в href, например href="#home"

2021-12-03 10:11 UTC, VladimirBludov commented on src/partials/header.html
> +          <use href="images/icons.svg#burger" width="14" height="14"></use>
width="14" height="14" переставь на свг

2021-12-03 10:11 UTC, VladimirBludov commented on src/sass/_header.scss
> +    background-color: #FFB8CA;
цвета используй с помощью функции getColor('название цвета из библиотеки'); например:
background-color:  getColor('bg-primary'); если такого цвета еще нет, добавь его в библиотеку в файл: _variables.scss

таким образом везде используй цвета

2021-12-03 10:11 UTC, VladimirBludov commented on src/sass/_header.scss
> +    cursor: pointer;
cursor: pointer; по умолчанию выставлен на все кнопки, он тут не нужен

2021-12-03 10:11 UTC, VladimirBludov commented on src/sass/_header.scss
> +    transition: color 250ms linear;
везде переход используй из переменой, вместо linear, $animation-cubic
и зачем тебе transition, если нет ховера, фокуса

2021-12-03 10:11 UTC, VladimirBludov commented on src/sass/_header.scss
> +    }
добавь в конце пустую строку

2021-12-04 22:50 UTC, VladimirBludov requested changes

2021-12-04 22:50 UTC, VladimirBludov commented on src/mobile-menu.js
> +  })();
добавь пустую строку в конце

2021-12-04 22:50 UTC, VladimirBludov commented on src/partials/header.html
> +      <use href="images/icons.svg#burger" width="20" height="12"></use>
width="20" height="12" переставь на свг

2021-12-04 22:50 UTC, VladimirBludov commented on src/partials/header.html
> +  <use href="images/icons.svg#arrow" width="2.26px" height="8"></use>
width="2.26px" height="8" переставь на свг и width поставь 5,26px

2021-12-04 22:50 UTC, VladimirBludov commented on src/partials/header.html
> +              <li class="mobile-nav__item"><a class="mobile-nav__link link" href="#contacts.html">Contact</a></li>
подтяни в свою ветку мейн и проставь якоря (айди на секции, где еще нет), и проверь чтобы работал переход

2021-12-04 22:50 UTC, VladimirBludov commented on src/partials/header.html
> +          <use href="images/icons.svg#close" width="14" height="14"></use>
width="14" height="14" переставь на свг

2021-12-04 22:50 UTC, VladimirBludov commented on src/sass/_header.scss
> +    height: 8px;
когда переставишь на свг, тут удали

2021-12-04 22:50 UTC, VladimirBludov commented on src/sass/_header.scss
> +    font-style: normal;
font-style: normal; удали

2021-12-04 22:50 UTC, VladimirBludov commented on src/sass/_header.scss
> +    font-weight: bold;
font-weight: bold; (все цифрами)  => font-weight: 700;

2021-12-04 22:50 UTC, VladimirBludov commented on src/sass/_header.scss
> +font-weight: bold;
тоже самое, что и выше

2021-12-05 09:07 UTC, AlinaSenkovich commented on src/sass/_header.scss
> +font-weight: bold;
+

2021-12-05 09:08 UTC, AlinaSenkovich commented on src/sass/_header.scss
> +font-weight: bold;
сделала

2021-12-05 09:08 UTC, AlinaSenkovich commented on src/sass/_header.scss
> +    font-weight: bold;
сделала

2021-12-05 09:08 UTC, AlinaSenkovich commented on src/sass/_header.scss
> +    font-style: normal;
сделала

2021-12-05 09:08 UTC, AlinaSenkovich commented on src/sass/_header.scss
> +    height: 8px;
сделала

2021-12-05 09:08 UTC, AlinaSenkovich commented on src/partials/header.html
> +          <use href="images/icons.svg#close" width="14" height="14"></use>
сделала

2021-12-05 09:09 UTC, AlinaSenkovich commented on src/partials/header.html
> +              <li class="mobile-nav__item"><a class="mobile-nav__link link" href="#contacts.html">Contact</a></li>
якоря поставила, но подтянуть мейн не получается

2021-12-05 09:10 UTC, AlinaSenkovich commented on src/partials/header.html
> +  <use href="images/icons.svg#arrow" width="2.26px" height="8"></use>
сделала

2021-12-05 09:10 UTC, AlinaSenkovich commented on src/partials/header.html
> +      <use href="images/icons.svg#burger" width="20" height="12"></use>
сделала

2021-12-05 09:10 UTC, AlinaSenkovich commented on src/mobile-menu.js
> +  })();
сделала

2021-12-05 10:21 UTC, VladimirBludov requested changes

2021-12-05 10:21 UTC, VladimirBludov commented on src/partials/header.html
> +<button class="mobile-btn mobile-btn-wrap" type="button" data-modal-open="1">Buy now<svg class="mobile-btn-icon" width="2.26px" height="8">
ширину другую писал, поменяй, вроде 5.26px по макету

2021-12-05 16:21 UTC, closed without merging