update
VladimirBludov/team-project-ice-cream pull request #17
Opened 2021-12-03 15:49 UTC by Mozgarik

2021-12-04 11:39 UTC, VladimirBludov commented
Пофикси конфликт

2021-12-04 11:49 UTC, VladimirBludov requested changes

2021-12-04 11:49 UTC, VladimirBludov commented on src/images/icons.svg
>  </svg>
верни на место))))

2021-12-04 11:49 UTC, VladimirBludov commented on src/index.js
> +import './up';
добавь пустую строку в конце

2021-12-04 11:49 UTC, VladimirBludov commented on src/modal.js
> +        modalAbout: document.querySelector('[data-modal]'),
если все будут использовать data-modal у кого-то все поломается, пусть Миша у себя в html их поубирает, а ты вместо 
openModalBtn: document.querySelector('[data-modal-open]'),
        closeModalBtn: document.querySelector('[data-modal-close]'),
        modalAbout: document.querySelector('[data-modal]'),

сделай:
openModalBtn: document.querySelector('.имя-класса'),
        closeModalBtn: document.querySelector('.имя-класса'),
        modalAbout: document.querySelector('.имя-класса'),

2021-12-04 11:49 UTC, VladimirBludov commented on src/modal.js
> +         modalAbout: document.querySelector('[modal]'),
ну и тут имена классов вместо дата атрибутов поставь

2021-12-04 11:49 UTC, VladimirBludov commented on src/partials/read_more.html
> +</div>
добавь пустую строку в конце

2021-12-04 11:49 UTC, VladimirBludov commented on src/partials/up.html
> +</div>
добавь пустую строку в конце

2021-12-04 11:49 UTC, VladimirBludov commented on src/sass/_up.scss
> +  }
добавь пустую строку в конце

2021-12-04 11:49 UTC, VladimirBludov commented on src/sass/main.scss
> +@import "./up";
добавь пустую строку в конце

2021-12-04 11:49 UTC, VladimirBludov commented on src/up.js
> +}
добавь пустую строку в конце

2021-12-04 13:15 UTC, Mozgarik commented on src/index.js
> +import './up';
добавил

2021-12-04 13:15 UTC, Mozgarik commented on src/modal.js
> +        modalAbout: document.querySelector('[data-modal]'),
сделал

2021-12-04 13:15 UTC, Mozgarik commented on src/partials/read_more.html
> +</div>
добавил

2021-12-04 13:15 UTC, Mozgarik commented on src/partials/up.html
> +</div>
добавил

2021-12-04 13:15 UTC, Mozgarik commented on src/sass/_up.scss
> +  }
добавил

2021-12-04 13:15 UTC, Mozgarik commented on src/sass/main.scss
> +@import "./up";
добавил

2021-12-04 13:16 UTC, Mozgarik commented on src/up.js
> +}
добавил

2021-12-04 20:04 UTC, VladimirBludov requested changes

2021-12-04 20:04 UTC, VladimirBludov commented on src/modal.js
> + })();
добавь пустую строку в конце

2021-12-04 20:04 UTC, VladimirBludov commented on src/sass/_read_more.scss
> +}
добавь анимацию появления и скрытия модалки

2021-12-04 22:45 UTC, Mozgarik commented on src/modal.js
> + })();
добавил

2021-12-05 09:02 UTC, VladimirBludov approved these changes

2021-12-05 09:02 UTC, merged