Feature hero tablet
VladimirBludov/team-project-ice-cream pull request #18
Opened 2021-12-03 17:25 UTC by PavloLevchenko

2021-12-03 17:49 UTC, VladimirBludov requested changes

2021-12-03 17:49 UTC, VladimirBludov commented on src/partials/hero.html
> +          srcset="
пример комита

2021-12-03 17:50 UTC, PavloLevchenko commented on src/partials/hero.html
> +          srcset="
пример решения

2021-12-04 10:49 UTC, VladimirBludov requested changes

2021-12-04 10:49 UTC, VladimirBludov commented on src/sass/_container.scss
> +  overflow: hidden;
здесь зачем оставил?

2021-12-04 10:49 UTC, VladimirBludov commented on src/sass/_hero.scss
>      margin-top: 19px;
20px

2021-12-04 12:51 UTC, PavloLevchenko commented on src/sass/_container.scss
> +  overflow: hidden;
Наверно подтянулось при мерже моих веток, убрал

2021-12-04 12:52 UTC, PavloLevchenko commented on src/sass/_hero.scss
>      margin-top: 19px;
Исправил

2021-12-04 13:00 UTC, VladimirBludov approved these changes

2021-12-04 13:00 UTC, merged